server:
  port: ${SERVER_PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  graphql:
    graphiql:
      enabled: true
