INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Elin', 'Bos', '1980-01-20');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Ruben', 'Dekker', '1962-09-15');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Klaas', 'Vos', '1990-07-14');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Noor', 'Peters', '2007-08-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Sara', 'Smit', '1967-07-18');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bart', 'Smit', '1999-08-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Isa', 'van der Meer', '2002-05-11');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Sara', 'Dekker', '2008-11-15');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Piet', 'de Boer', '1979-02-15');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Klaas', 'Vos', '1999-06-12');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Elin', 'Vos', '1966-04-12');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Lotte', 'Bos', '1996-02-07');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Tess', 'Dekker', '1991-07-08');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Laura', 'Meijer', '1984-03-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Johan', 'Jansen', '1988-03-27');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Maud', 'Vermeulen', '1957-09-05');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Fleur', 'de Boer', '1993-05-03');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Sara', 'van Dijk', '1967-03-12');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Linda', 'de Boer', '1955-02-24');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Jan', 'de Vries', '1988-11-07');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Sophie', 'de Vries', '1984-12-21');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Piet', 'Jansen', '1958-05-16');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Luuk', 'Vermeulen', '1983-04-13');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Tom', 'Meijer', '1977-01-23');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Dirk', 'van Dijk', '1984-09-06');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Koen', 'Peters', '1974-12-02');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bart', 'Meijer', '1964-07-22');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Iris', 'Vos', '2001-05-14');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Ruben', 'de Boer', '2004-10-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Iris', 'Schouten', '1977-12-06');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Noa', 'Peters', '1968-07-21');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Esmee', 'van Dijk', '1965-11-27');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Anna', 'Meijer', '1971-08-29');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Martijn', 'de Vries', '2002-05-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Anouk', 'Smit', '1952-11-07');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Lars', 'Mulder', '1983-02-12');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Wim', 'Jansen', '1956-08-25');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Lisa', 'Koster', '1970-08-12');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Piet', 'Dekker', '1969-01-08');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Isa', 'Jansen', '1985-08-13');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Luuk', 'Kok', '1981-01-19');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bo', 'Bos', '1964-02-15');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Fleur', 'van Dijk', '1989-11-26');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Noa', 'Meijer', '1980-11-25');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bart', 'Bakker', '1966-12-19');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bart', 'Vermeulen', '2001-10-01');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Roos', 'Visser', '1995-04-04');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Bart', 'Hendriks', '1991-01-31');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Koen', 'Dekker', '1986-09-23');
INSERT INTO persoon (first_name, last_name, date_of_birth) VALUES ('Julia', 'de Boer', '2003-07-04');